run-name: Payload from ${{ github.event_name }} event

on:
  pull_request:
    types: [opened, closed, reopened]
  push:
  workflow_dispatch:

jobs:
  printJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Action local
        uses: ./
        with:
          secretList: 'SECRET_A'
