run-name: Payload from ${{ github.event_name }} event

on:
  pull_request:
    types: [opened, closed, reopened]
  push:
  workflow_dispatch:

jobs:
  wait1:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 10
  wait2:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 10
